# decaysim
# Parameters and settings

[params]

tau_seed = 0.0239 # in [s]

timestep = 0.00922  # in [s]
n_sim_steps = 108 # approx. 5 s total, time after injection

n_sim = 102   # 32 number of simulated decays in setting 1
n_trials = 1000

n_decay_steps = 0  # either 0 or 1

mean_ion_number = 2
max_ions = 4
noise_model = "linear"
mean_ion = 7.3E-05
stdv_ion = 3.5E-05  # MEAN_ION * 0.082

mean_bkgnd = 3.4E-05
stdv_bkgnd = 1.5E-05 # MEAN_BKGND * 0.038

empty_shots = false
empty_shots_probability = 0.0

limit = 100

[settings]

tasks = ['addup', 'mle'] # Tasks: what to simulate, like 'addup', 'distro', 'mle'i
output_path = "./out_ge"
plot_every_event = false # expect longer simulation times if set to true. applies only to addup method
save_npz = false
plot_titles = false # turn plot titles on or off

