# decaysim
# Parameters and settings

[params]

tau_seed = 0.13099 # in [s]

timestep = 0.009  # in [s]
n_sim_steps = 179 # approx. 1.6 s total time after injection

n_sim = 300  # 32 number of simulated decays in setting 1
n_trials = 1000

n_decay_steps = 0  # either 0 or 1

mean_ion_number = 18
max_ions = 50

noise_model = "linear" # "sqrt" or "linear"
mean_ion = 2.72
stdv_ion = 0.86 # MEAN_ION * 0.082

mean_bkgnd = 1.67
stdv_bkgnd = 0.59 # MEAN_BKGND * 0.038

empty_shots = false
empty_shots_probability = 0.0

limit = 200

seed = 42  # fixes the RNG for reproducible runs; omit/remove for nondeterministic runs

[settings]

tasks = ['addup', 'mle'] # Tasks: what to simulate, like 'addup', 'distro', 'mle'
output_path = "./out_mo"
plot_every_event = false # expect longer simulation times if set to true. applies only to addup method
save_npz = true
plot_titles = false # turn plot titles on or off
